### ISSUE TITLE
Outdated NPM release.

### ISSUE THREAD

**Issue by kinsi55** [jerolimov/comprise#2]
Seems like you forgot the version in the package.js with [the last update](https://github.com/jerolimov/comprise/commit/1d987aecab81f383d389085e6cc6e094a31c88fd). If this package is now unmaintained - do you know of an alternative? Thanks!

**Comment by christoph-jerolimov** [comment]
@kinsi55 Did you tested it if it still works or can you create an update and a PR?

**Comment by kinsi55** [comment]
@jerolimov I actually just now realized that I'm not even using comprise (anymore), I thought I did because I went trough my package file and remembered the name but turns out I've switched it out for a different solution a while ago. Sorry for the disturbance. Feel free to close

**Comment by christoph-jerolimov** [comment]
Okay, have a nice day
